using System.ComponentModel.DataAnnotations;

namespace GameStore.Api.Dtos;

public record CreateGameDto(
    [Required][StringLength(50)] string Name,
    [Range (1, 50)] int GenreId,
    [Range(1, 100)]decimal Price,
    DateOnly ReleaseDate
);

// This DTO is used for creating a new game, it does not include the Id property since the Id will be generated by the server when a new game is created.